defmodule LCSchemas.Schema do
  @moduledoc false

  defmacro __using__(:relational) do
    quote do
      use Ecto.Schema

      @primary_key {:id, :id, autogenerate: true}
      @foreign_key_type :id
      @timestamps_opts [type: :utc_datetime_usec]
    end
  end

  defmacro __using__(:uuid_primary_key) do
    quote do
      use Ecto.Schema

      # Token IDs are generated by Postgres, so reads after insert must populate :id.
      @primary_key {:id, :binary_id, autogenerate: false, read_after_writes: true}
      @foreign_key_type :id
      @timestamps_opts [type: :utc_datetime_usec]
    end
  end
end
