defmodule LCSchemas do
  @moduledoc false

  use Boundary,
    top_level?: true,
    exports: [
      Accounts,
      Accounts.AuthEvent,
      Accounts.AuthEventType,
      Accounts.EmailAddress,
      Accounts.PhoneNumber,
      Accounts.User,
      Accounts.UserPrivacyMode,
      Accounts.UserContactEntry,
      Accounts.UserContactEntryEmailAddress,
      Accounts.UserContactEntryPhoneNumber,
      Accounts.UserEmailAddress,
      Accounts.UserIdentity,
      Accounts.UserIdentityProvider,
      Accounts.UserPhoneNumber,
      Accounts.UserToken,
      Accounts.UserTokenContext,
      Social,
      Social.Block,
      Social.Follow,
      Social.FollowState,
      Social.Mute,
      Content,
      Content.Post,
      Content.MediaAsset,
      Chat,
      Chat.ChatMessage,
      Live,
      Live.LiveParticipant,
      Live.LiveSession,
      Live.LiveSessionRuntimeOwner,
      Infra,
      Infra.AsyncJob,
      Infra.WebhookEvent
    ]
end
